import "./globals.css";
import type { Metadata } from "next";
import {Lato,Manrope } from "next/font/google";
import StyledComponentsRegistry from "@/helpers/registry";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  preload: true,
  style: "normal",
  variable: "--font-manrope",
});
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  preload: true,
  style: "normal",
  variable: "--font-lato",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable} ${lato.variable}`}>  
      <body>
        <StyledComponentsRegistry>
          {children}
          </StyledComponentsRegistry>
      </body>
    </html>
  );
}
